name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (features = default)
      run: cargo build --verbose
    - name: Build (features = rpc)
      run: cargo build --verbose --no-default-features --features rpc
    - name: Build (features = stealth)
      run: cargo build --verbose --no-default-features --features stealth

    - name: Run tests (features = default)
      run: cargo test --verbose
