name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (features = default)
      run: cargo build --verbose
    - name: Build (features = rpc)
      run: cargo build --verbose --no-default-features --features rpc
    - name: Build (features = stealth)
      run: cargo build --verbose --no-default-features --features stealth
    - name: Build (features = serde)
      run: cargo build --verbose --no-default-features --features serde

    - name: Run Tests (features = all)
      run: cargo test --verbose --all-features

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features