name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (features = default)
      run: cargo build --verbose
    - name: Build (features = rpc)
      run: cargo build --verbose --no-default-features --features rpc
    - name: Build (features = camo)
      run: cargo build --verbose --no-default-features --features camo
    - name: Build (features = serde)
      run: cargo build --verbose --no-default-features --features serde

    - name: Run Tests (features = all)
      run: cargo test --verbose --all-features

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features